### ISSUE TITLE
Roadmap (User Stories)

### ISSUE THREAD

**Issue by franciscocandido** [franciscocandido/say-hello#1]
- [x] User can see a mock login panel containing a user name text input field and 'Login' button.

- [x] User can enter a mock login name into the User Name field.

- [x] User can click the 'Login' button to perform a mock login.

- [x] User can see an additional text input field for a language code which will be used to override the IP obtained through geolocation.
- [x] User can see a new message when successfully logged out in the format: `<hello-in-native-language> <user-name>`
